wagtail/contrib/redirects/urls.py
from django.urls import path

from wagtail.contrib.redirects import views

app_name = "wagtailredirects"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("results/", views.IndexView.as_view(results_only=True), name="index_results"),
    path("add/", views.CreateView.as_view(), name="add"),
    path("<int:redirect_id>/", views.EditView.as_view(), name="edit"),
    path("<int:redirect_id>/delete/", views.DeleteView.as_view(), name="delete"),
    path("import/", views.start_import, name="start_import"),
    path("import/process/", views.process_import, name="process_import"),
]

wagtail/contrib/redirects/templates/wagtailredirects/add.html
{% extends "wagtailadmin/generic/create.html" %}

wagtail/contrib/redirects/templates/wagtailredirects/choose_import_file.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}
{% block titletag %}{% trans "Redirects" %}{% endblock %}

{% block content %}
    {% trans "Import redirects" as header_title %}
    {% include "wagtailadmin/shared/header.html" with title=header_title icon="redirect" %}

    <div class="nice-padding">
        <div class="help-block help-info">
            {% icon name='help' %}
            {% blocktrans trimmed %}
                <p>Select a file where redirects are separated into rows and contains the columns representing <code>from</code> and <code>to</code> (they can be named anything).</p>
                <p>After submitting you will be taken to a confirmation view where you can customize your redirects before import.</p>
            {% endblocktrans %}
        </div>
    </div>

    {% include "wagtailadmin/shared/non_field_errors.html" %}

    <form action="" method="POST" class="nice-padding" novalidate enctype="multipart/form-data">
        {% csrf_token %}

        <ul class="fields">
            {% for field in form.visible_fields %}
                <li>{% formattedfield field %}</li>
            {% endfor %}

            <li>
                <input type="submit" value="{% trans 'Import' %}" class="button" />
            </li>
        </ul>
    </form>
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/confirm_delete.html
{% extends "wagtailadmin/generic/confirm_delete.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans trimmed with title=redirect.title %}Delete redirect {{ title }}{% endblocktrans %}{% endblock %}
{% block confirmation_message %}
    <p>{% trans "Are you sure you want to delete this redirect?" %}</p>
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/confirm_import.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}

{% block titletag %}{% trans "Confirm import" %}{% endblock %}
{% block content %}
    {% trans "Import redirects" as header_title %}
    {% trans "Confirm import" as header_subtitle %}
    {% include "wagtailadmin/shared/header.html" with title=header_title subtitle=header_subtitle icon="redirect" %}

    {% include "wagtailadmin/shared/non_field_errors.html" %}

    <form action="{% url 'wagtailredirects:process_import' %}" method="POST" class="nice-padding" novalidate enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form.hidden_fields %}{{ field }}{% endfor %}

        <ul class="fields">
            {% for field in form.visible_fields %}
                <li>{% formattedfield field %}</li>
            {% endfor %}

            <li>
                <input type="submit" value="{% trans 'Confirm' %}" class="button" />
                <a href="{% url 'wagtailredirects:index' %}" class="button button-secondary">
                    {% trans 'Cancel' %}
                </a>
            </li>
        </ul>

        <h2>{% trans "Preview" %}</h2>
        <table class="listing listing-with-x-scroll">
            <thead>
                <tr>
                    {% for column in dataset.headers %}
                        <td>{{ column }}</td>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row in dataset %}
                    <tr>
                        {% for column in row %}
                            <td>{{ column }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/edit.html
{% extends "wagtailadmin/generic/edit.html" %}

wagtail/contrib/redirects/templates/wagtailredirects/import_summary.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}
{% block titletag %}{% trans "Summary" %}{% endblock %}
{% block content %}
    {% trans "Import redirects" as header_title %}
    {% trans "Summary" as header_subtitle %}
    {% include "wagtailadmin/shared/header.html" with title=header_title subtitle=header_subtitle icon="redirect" %}
    <section id="summary" class="nice-padding">
        <p class="help-block help-warning">
            {% icon name='warning' %}
            {% blocktrans trimmed with total=import_summary.total|intcomma successes=import_summary.successes|intcomma errors=import_summary.errors_count|intcomma %}Found {{ total }} redirects, created {{ successes }} and found {{ errors }} errors.{% endblocktrans %}
        </p>

        <table class="listing">
            <thead>
                <tr>
                    <th>{% trans "From" %}</th>
                    <th>{% trans "To" %}</th>
                    <th>{% trans "Error" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for error in import_summary.errors %}
                    <tr>
                        {% for value in error %}
                            <td>{{ value }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a href="{% url 'wagtailredirects:index' %}" class="button">{% trans "Continue" %}</a>
    </section>
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/index.html
{% extends "wagtailadmin/generic/index.html" %}

wagtail/contrib/redirects/templates/wagtailredirects/index_results.html
{% extends "wagtailadmin/generic/index_results.html" %}
{% load i18n %}

{% block no_results_message %}
    {% if query_string %}
        <p role="alert">
            {% blocktrans trimmed %}
                Sorry, no redirects match "<em>{{ query_string }}</em>"
            {% endblocktrans %}
        </p>
    {% else %}
        <p>
            {% blocktrans trimmed with wagtailredirects_add_redirect_url=add_url %}
                No redirects have been created. Why not <a href="{{ wagtailredirects_add_redirect_url }}">add one</a>?
            {% endblocktrans %}
        </p>
    {% endif %}
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/redirect_target_cell.html
{% load i18n wagtailadmin_tags %}
<td class="w-truncate w-max-w-0">
    {% if url %}
        <a href="{{ url }}" class="nolink">{{ value }}</a>
    {% else %}
        {{ value }}
    {% endif %}
</td>