wagtail/contrib/forms/urls.py
from django.urls import path

from wagtail.contrib.forms.views import (
    DeleteSubmissionsView,
    FormPagesListView,
    get_submissions_list_view,
)

app_name = "wagtailforms"
urlpatterns = [
    path("", FormPagesListView.as_view(), name="index"),
    path(
        "results/", FormPagesListView.as_view(results_only=True), name="index_results"
    ),
    path(
        "submissions/<int:page_id>/", get_submissions_list_view, name="list_submissions"
    ),
    path(
        "submissions/<int:page_id>/results/",
        get_submissions_list_view,
        {"results_only": True},
        name="list_submissions_results",
    ),
    path(
        "submissions/<int:page_id>/delete/",
        DeleteSubmissionsView.as_view(),
        name="delete_submissions",
    ),
]

wagtail/contrib/forms/templates/wagtailforms/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans trimmed with title=page.title %}Delete form data {{ title }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-explorer{% endblock %}

{% block content %}
    {% trans "Delete form data" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str subtitle=page.title icon="doc-empty-inverse" %}

    <div class="nice-padding">
        <p>
            {% blocktrans trimmed count counter=submissions.count %}
                Are you sure you want to delete this form submission?
            {% plural %}
                Are you sure you want to delete these form submissions?
            {% endblocktrans %}
        </p>
        <form action="{% url 'wagtailforms:delete_submissions' page.id %}?{{ request.GET.urlencode }}" method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{ next_url }}" name="next">
            <input type="submit" value="{% trans 'Delete' %}" class="button serious">
        </form>
    </div>
{% endblock %}

wagtail/contrib/forms/templates/wagtailforms/content_type_column.html
<td {% if column.classname %}class="{{ column.classname }}"{% endif %}>
    <small><a href="{{ url }}" class="nolink">{{ value.name |capfirst }} ({{ value.app_label }}.{{ value.model }})</a></small>
</td>

wagtail/contrib/forms/templates/wagtailforms/index.html
{% extends "wagtailadmin/pages/listing.html" %}

wagtail/contrib/forms/templates/wagtailforms/index_results.html
{% extends "wagtailadmin/generic/listing_results.html" %}

wagtail/contrib/forms/templates/wagtailforms/list_submissions.html
{% extends "wagtailadmin/generic/listing_results.html" %}
{% load i18n l10n %}
{% block results %}
    <form class="w-overflow-auto" data-controller="w-bulk" data-w-bulk-action-inactive-class="w-invisible" action="{% url 'wagtailforms:delete_submissions' form_page.id %}" method="get">
        <input type="hidden" value="{{ next_url }}" name="next">
        <table class="listing">
            <col />
            <col />
            <col />
            <thead>
                <tr>
                    <th><input type="checkbox" data-action="w-bulk#toggleAll" data-w-bulk-target="all" /></th>
                    {% for heading in data_headings %}
                        <th id="{{ heading.name }}" class="{% if heading.order %}ordered icon {% if heading.order == 'ascending' %}icon-arrow-up-after{% else %}icon-arrow-down-after{% endif %}{% endif %}">
                            {% if heading.order %}<a href="?order_by={% if heading.order == 'ascending' %}-{% endif %}{{ heading.name }}">{{ heading.label }}</a>{% else %}{{ heading.label }}{% endif %}
                        </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row in data_rows %}
                    <tr>
                        <td>
                            <input type="checkbox" name="selected-submissions" class="select-submission" value="{{ row.model_id|unlocalize }}" data-action="w-bulk#toggle" data-w-bulk-target="item" />
                        </td>
                        {% for cell in row.fields %}
                            <td>
                                {{ cell }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="nice-padding">
            <button class="button no w-invisible" data-w-bulk-target="action">
                {% trans "Delete selected submissions" %}
            </button>
        </div>
    </form>
{% endblock %}

{% block no_results_message %}
    <p>
        {% blocktrans trimmed with title=form_page.title %}
            There have been no submissions of the '{{ title }}' form.
        {% endblocktrans %}
    </p>
{% endblock %}

wagtail/contrib/forms/templates/wagtailforms/submissions_index.html
{% extends "wagtailadmin/generic/listing.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans trimmed with form_title=form_page.title|capfirst %}Submissions of {{ form_title }}{% endblocktrans %}{% endblock %}